name: Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment (dev, qa, or both)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - both

jobs:
  deploy:
    if: github.event.inputs.environment != 'none'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, qa]

    steps:
      - name: Skip environment if not selected
        if: github.event.inputs.environment != 'both' && github.event.inputs.environment != matrix.env
        run: echo "Skipping ${{ matrix.env }} environment."

      - name: Deploy to environment
        if: github.event.inputs.environment == 'both' || github.event.inputs.environment == matrix.env
        env:
          KUBECONFIG: ${{ secrets[format('KUBECONFIG_{0}', toUpper(matrix.env))] }}
        run: |
          echo "Deploying to ${{ matrix.env }}..."
          # Your deployment logic goes here, e.g.:
          # kubectl --kubeconfig="$KUBECONFIG" apply -f deployment.yaml
